name: build Nightly

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows-amd64:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: Inall NSIS EnVar Plugin
        run: |
          curl -L https://github.com/GsNSIS/EnVar/releases/download/v0.3.1/EnVar-Plugin.zip -o EnVar-Plugin.zip &&
          unzip EnVar-Plugin.zip -d "C:\Program Files (x86)\NSIS"

      - name: Setup Dependency Walker
        run: |
          curl -L https://dependencywalker.com/depends22_x64.zip -o depends22_x64.zip && 
          unzip depends22_x64.zip -d C:\Users\eric\AppData\Local\Nuitka\Nuitka\depends\x86_64
      
      - name: Set up MinGW
        uses: ericCHxia/setup-mingw@v3
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      
      - name: Install Dependence
        run: |
          pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Build
        run: |
          Get-Command g++
          Get-Command gcc
          Get-Command python
          python build.py --pack
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jdkmgr_${{github.ref_name}}_windows_amd64.zip
          path: artifact
          retention-days: 7
